### ISSUE TITLE
Interested in this work

### ISSUE THREAD

**Issue by smolinari** [catmeme/vue-adminlte#1]
Hi,

I am liking the work being done here, however, I'd personally like to see it done purely with Vue.js. Check out vue-strap for an idea about what I mean. https://github.com/yuche/vue-strap

Scott

**Comment by catmeme** [comment]
Hello,

Thank you for you interest. I agree it would be nice to have it all coded in Vue.js. For the time being I'm experimenting with how far I can take AdminLTE with minimal changes and turn it into a Single Page App using Vue. After I get myself a bit more acquainted with Vue.js, I can start refactoring some of the AdminLTE app and demo code.

The jQuery plugins can be quite complex and will probably not be re-implemented, at least not by me.

I'm open to any help or advice moving forward :)

**Comment by smolinari** [comment]
Yeah, looking at all the jQuery and other libraries needed for a lot of the functionality, I can see what you mean. I guess what is important is the ability to get the data into the different components, where it is needed, in order for the application to be properly reactive. I can imagine that is a lot easier to say than do too. (I am personally not a very good JS programmer). So, I won't be much of help. I am still very interested in your work. Thanks for giving it a shot!

Scott

**Comment by smolinari** [comment]
How's the work coming along @catmeme?

Scott

**Comment by catmeme** [comment]
@smolinari I haven't had much time for this recently as the application I started this for has a tight deadline and high reliance on jQuery plugins. We've gone forward implementing the application without Vue.js for the moment but when I have some downtime after delivery, I can look into refactoring it for Vue.js and revisit this.
